package main

// DO NOT MODIFY: generated by github.com/ttacon/toml2cli
// If you need to make changes, update the toml config and then regenerate
// this file.

import (
	"log"
	"os"

	cli "github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Name = "artifact"
	app.Usage = "Helps build deployable artifacts."

	app.Commands = []*cli.Command{
		&cli.Command{
			Description: "Build deployable artifact",
			Name:        "build",
			Action:      build,
			Aliases:     []string{"b"},
			Flags: []cli.Flag{
				&cli.BoolFlag{
					Name:    "dry-run",
					Aliases: []string{"dry"},
				},
				&cli.StringFlag{
					Name:    "working-directory",
					Aliases: []string{"C"},
				},
				&cli.StringFlag{
					Name:    "git-range-start",
					Aliases: []string{"start"},
				},
				&cli.StringFlag{
					Name:    "git-range-end",
					Aliases: []string{"end"},
				},
				&cli.StringFlag{
					Name:    "cmd-prefix",
					Value:   "./cmd/",
					Aliases: []string{"pre"},
				},
				&cli.BoolFlag{
					Name: "skip-nested-entrypoints",
				},
				&cli.StringFlag{
					Name:    "repo-basename",
					Aliases: []string{"repo"},
				},
				&cli.StringFlag{
					Name:  "out-format",
					Value: "txt",
				},
				&cli.StringFlag{
					Name:  "build-command",
					Value: "go build -o build.artifact {{entrypoint}}",
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
